name: Deploy project to Deno server on need

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to deploy. Options: mihomo-subs-converter / nodes-collector / xlsx2csv-demo'
        default: 'mihomo-subs-converter'
        required: true
        type: string

permissions:
  id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
  contents: read

jobs:
  deploy-to-deno:
    runs-on: ubuntu-latest

    steps:
    - name: Setup deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Install deployctl
      run: |
        echo "Deno version is ${{ steps.deno.outputs.deno-version }}"
        deno install -gArf jsr:@deno/deployctl
        deployctl --version
      
    - name: Project deployment
      if: ${{ contains(fromJSON('["mihomo-subs-converter", "nodes-collector", "xlsx2csv-demo"]'), inputs.project) }}
      run: |
        echo "Deploy project '${{ inputs.project }}'"
        cd ${{ github.workspace }}/${{ inputs.project }}
        deno task deploy

    - name: Input not match
      if: ${{ !contains(fromJSON('["mihomo-subs-converter", "nodes-collector", "xlsx2csv-demo"]'), inputs.project) }}
      run: echo "Project '${{ inputs.project }}' is invaild."
    
